//! Rollup host: orchestrates Risc0 proving for L2 batches.
//!
//! Receives a Batch + current UTXO set, invokes the guest inside the zkVM,
//! and returns the STARK proof + BatchJournal for submission to the L1 verifier.

use borsh::BorshDeserialize;
use risc0_zkvm::{ExecutorEnv, ProverOpts, Receipt, default_prover};
use sophis_rollup_core::{Batch, BatchJournal, L2Utxo};
use thiserror::Error;

// ELF and image ID generated by risc0-build from rollup/guest
mod methods {
    include!(concat!(env!("OUT_DIR"), "/methods.rs"));
}

pub use methods::{SOPHIS_ROLLUP_GUEST_ELF, SOPHIS_ROLLUP_GUEST_ID};

#[derive(Debug, Error)]
pub enum ProverError {
    #[error("risc0 execution error: {0}")]
    Execution(String),
    #[error("journal deserialization error: {0}")]
    Journal(String),
    #[error("proof verification failed: {0}")]
    Verification(String),
}

pub struct ProofOutput {
    pub receipt: Receipt,
    pub journal: BatchJournal,
}

/// Prove a batch state transition.
/// - `batch`: the batch to prove
/// - `utxo_set`: all live L2 UTXOs at `batch.prev_state_root`
pub fn prove_batch(batch: Batch, utxo_set: Vec<L2Utxo>) -> Result<ProofOutput, ProverError> {
    // Risc0's write() uses serde; our types use borsh. Encode to Vec<u8> first,
    // then write the byte vec (Vec<u8> is serde-compatible).
    let batch_bytes = borsh::to_vec(&batch).map_err(|e| ProverError::Execution(e.to_string()))?;
    let utxos_bytes = borsh::to_vec(&utxo_set).map_err(|e| ProverError::Execution(e.to_string()))?;
    let env = ExecutorEnv::builder()
        .write(&batch_bytes)
        .map_err(|e| ProverError::Execution(e.to_string()))?
        .write(&utxos_bytes)
        .map_err(|e| ProverError::Execution(e.to_string()))?
        .build()
        .map_err(|e| ProverError::Execution(e.to_string()))?;

    let prover = default_prover();
    let receipt = prover
        .prove_with_opts(env, SOPHIS_ROLLUP_GUEST_ELF, &ProverOpts::default())
        .map_err(|e| ProverError::Execution(e.to_string()))?
        .receipt;

    // Verify the receipt locally before returning
    receipt.verify(SOPHIS_ROLLUP_GUEST_ID).map_err(|e| ProverError::Verification(e.to_string()))?;

    // Decode the public journal (borsh, consistent with guest's commit_slice)
    let journal: BatchJournal = borsh::from_slice(&receipt.journal.bytes).map_err(|e| ProverError::Journal(e.to_string()))?;

    Ok(ProofOutput { receipt, journal })
}

/// Verify a receipt without re-proving (used by the sequencer before L1 submission).
pub fn verify_receipt(receipt: &Receipt) -> Result<BatchJournal, ProverError> {
    receipt.verify(SOPHIS_ROLLUP_GUEST_ID).map_err(|e| ProverError::Verification(e.to_string()))?;

    borsh::from_slice(&receipt.journal.bytes).map_err(|e| ProverError::Journal(e.to_string()))
}
